version: '3.5'
services:
  nginx:
    image: nginx:alpine
    container_name: sklad-nginx
    working_dir: /var/www/sklad
    volumes:
      - ./:/var/www/sklad
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - postgres
    depends_on:
      - php
      - postgres
    ports:
      - ${NGINX_PORT}:80
  php:
    container_name: sklad-php
    build:
      context: .docker/php
      dockerfile: ${PHP_DOCKERFILE}
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    extra_hosts:
        - "${HOST_DOCKER_INTERNAL}:host-gateway"
    volumes:
      - ./:/var/www/sklad
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini:delegated
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:delegated
    working_dir: /var/www/sklad
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - ${PHP_PORT}:9000
  postgres:
    container_name: sklad-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/sklad/postgres
    volumes:
      - postgres:/data/sklad/postgres
    ports:
      - ${POSTGRES_PORT}:5432
volumes:
    postgres:
        external: true

